volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local

services:

  postgres:
    image: postgres:15
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 100
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/scripts
    env_file:
      - services/.env.local
    environment:
      POSTGRES_PASSWORD: password
      PGUSER: postgres
    ports:
      - "5432:5432"
  redis:
    build:
      dockerfile: docker/redis.Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

