services:
  postgres:
    image: postgres:14
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 100
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGPORT: ${PG_PORT}
      PGUSER: ${PG_USER}
    volumes:
      - ./scripts:/scripts
    ports:
      - "${PG_PORT}:${PG_PORT}"
