volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

services:

  postgres:
    image: postgres:15
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 100
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/scripts
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: password
      PGUSER: postgres
    ports:
      - "5432:5432"

  api:
    image: api:${GIT_TAG}
    container_name: api
    depends_on:
      gateway:
        condition: service_healthy
    env_file:
      - .env
      - .env.credentials
    environment:
      PORT: ${API_PORT}
    ports:
      - "3000:${API_PORT}"

  gateway:
    image: gateway:${GIT_TAG}
    container_name: gateway
    healthcheck:
      test: curl http://localhost:$$GATEWAY_PORT/api/v1/healthz
      interval: 3s
      timeout: 1s
      retries: 30
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
      - .env.credentials
    environment:
      DB_URL: ${DB_URL}
      PORT: ${GATEWAY_PORT}
    ports:
      - "8080:${GATEWAY_PORT}"
