openapi: "3.0.0"
info:
  version: 1.0.0
  title: WTF Rest API
  contact:
    url: https://dev.what-da-flac.com
servers:
  - url: http://localhost:8000/api
  - url: https://dev.what-da-flac.com/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [ ]
paths:

  /v1/healthz:
    $ref: './resources/health.yaml'


  /v1/files:
    $ref: './resources/file-post.yaml'