Description: Builds wtf-go-builder image and deploys to ecr
Docker:
  Type: aws
ComputeType: SMALL
Environments:
  - Name: SSH_PRIVATE_KEY
    Type: secret
    Value: mauleyzaola-private-key
  - Name: GITHUB_ACCESS_TOKEN
    Type: secret
    Value: gh-token
Id: wtf-go-releaser-deployment
InlinePolicies:
  ecr:
    Action: ecr:*
    Resources:
      - arn:aws:ecr:*:*
  secrets:
    Action: secretsmanager:GetSecretValue
    Resources:
      - arn:aws:secretsmanager:*:*
ManagedPolicies:
  - AmazonEC2ContainerRegistryPowerUser
Name: docker-releaser
Privileged: true
Source:
  CodebuildScriptPath: docker.yaml
  Repo: wtf
  Owner: what-da-flac
  Filter: tag-release
  PatternMatching: ^refs/tags/docker.*
