Description: Runs cdk diff on each commit pushed within a pr scope
Docker:
  Type: custom
  Url: 160885250498.dkr.ecr.us-east-2.amazonaws.com/wtf-go-builder:latest
ComputeType: MEDIUM
Environments:
  - Name: SSH_PRIVATE_KEY
    Type: secret
    Value: mauleyzaola-private-key
  - Name: GO_PRIVATE
    Type: text
    Value: github.com/tech-component/*
Id: wtf-deployment-pr-checker
InlinePolicies:
  secrets:
    Action: secretsmanager:GetSecretValue
    Resources:
      - arn:aws:secretsmanager:*:*
  ecr:
    Action: ecr:*
    Resources:
      - "*"
  cloudformation:
    Action: cloudformation:*
    Resources:
      - "*"
  s3-all:
    Action: s3:*
    Resources:
      - "*"
  iam:
    Action: iam:*
    Resources:
      - "*"
  lambda:
    Action: lambda:*
    Resources:
      - "*"
  ssm:
    Action: ssm:*
    Resources:
      - "*"
Name: wtf-deployment-pr-checker
Source:
  CodebuildScriptPath: codebuild/pr-checker.yaml
  Repo: wtf-deployment
  Owner: tech-component
  Filter: pull-request

