name: Services PR Checker

on:
  pull_request:
    branches: [ main, master ] # Triggers on PRs to main or master branches

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for proper branch comparison

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Configure Git
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"

    - name: Get default branch
      id: default-branch
      run: |
        DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | awk '{print $NF}')
        echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install moq
      run: |
        make -C services/ mock-install
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Run PR validation
      run: |
        make -C services/ test-all 
